// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: proto/notification.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { Metadata } from "@grpc/grpc-js";

export const protobufPackage = "notification";

export interface SendPaymentNotificationRequest {
  to: string;
  orderId: string;
}

export interface SendPaymentNotificationResponse {
  from: string;
  to: string;
  subject: string;
  content: string;
  status: string;
}

function createBaseSendPaymentNotificationRequest(): SendPaymentNotificationRequest {
  return { to: "", orderId: "" };
}

export const SendPaymentNotificationRequest: MessageFns<SendPaymentNotificationRequest> = {
  encode(message: SendPaymentNotificationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.to !== "") {
      writer.uint32(10).string(message.to);
    }
    if (message.orderId !== "") {
      writer.uint32(18).string(message.orderId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendPaymentNotificationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendPaymentNotificationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendPaymentNotificationRequest {
    return {
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
    };
  },

  toJSON(message: SendPaymentNotificationRequest): unknown {
    const obj: any = {};
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendPaymentNotificationRequest>, I>>(base?: I): SendPaymentNotificationRequest {
    return SendPaymentNotificationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendPaymentNotificationRequest>, I>>(
    object: I,
  ): SendPaymentNotificationRequest {
    const message = createBaseSendPaymentNotificationRequest();
    message.to = object.to ?? "";
    message.orderId = object.orderId ?? "";
    return message;
  },
};

function createBaseSendPaymentNotificationResponse(): SendPaymentNotificationResponse {
  return { from: "", to: "", subject: "", content: "", status: "" };
}

export const SendPaymentNotificationResponse: MessageFns<SendPaymentNotificationResponse> = {
  encode(message: SendPaymentNotificationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from !== "") {
      writer.uint32(10).string(message.from);
    }
    if (message.to !== "") {
      writer.uint32(18).string(message.to);
    }
    if (message.subject !== "") {
      writer.uint32(26).string(message.subject);
    }
    if (message.content !== "") {
      writer.uint32(34).string(message.content);
    }
    if (message.status !== "") {
      writer.uint32(42).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendPaymentNotificationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendPaymentNotificationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.from = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.to = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.subject = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendPaymentNotificationResponse {
    return {
      from: isSet(object.from) ? globalThis.String(object.from) : "",
      to: isSet(object.to) ? globalThis.String(object.to) : "",
      subject: isSet(object.subject) ? globalThis.String(object.subject) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
    };
  },

  toJSON(message: SendPaymentNotificationResponse): unknown {
    const obj: any = {};
    if (message.from !== "") {
      obj.from = message.from;
    }
    if (message.to !== "") {
      obj.to = message.to;
    }
    if (message.subject !== "") {
      obj.subject = message.subject;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendPaymentNotificationResponse>, I>>(base?: I): SendPaymentNotificationResponse {
    return SendPaymentNotificationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendPaymentNotificationResponse>, I>>(
    object: I,
  ): SendPaymentNotificationResponse {
    const message = createBaseSendPaymentNotificationResponse();
    message.from = object.from ?? "";
    message.to = object.to ?? "";
    message.subject = object.subject ?? "";
    message.content = object.content ?? "";
    message.status = object.status ?? "";
    return message;
  },
};

export interface NotificationService {
  sendPaymentNotification(
    request: SendPaymentNotificationRequest,
    metadata?: Metadata,
  ): Promise<SendPaymentNotificationResponse>;
}

export const NotificationServiceServiceName = "notification.NotificationService";
export class NotificationServiceClientImpl implements NotificationService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || NotificationServiceServiceName;
    this.rpc = rpc;
    this.sendPaymentNotification = this.sendPaymentNotification.bind(this);
  }
  sendPaymentNotification(
    request: SendPaymentNotificationRequest,
    metadata?: Metadata,
  ): Promise<SendPaymentNotificationResponse> {
    const data = SendPaymentNotificationRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "SendPaymentNotification", data, metadata);
    return promise.then((data) => SendPaymentNotificationResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array, metadata?: Metadata): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
