// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: proto/order.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { Metadata } from "@grpc/grpc-js";

export const protobufPackage = "order";

export interface DeliveryStartedRequest {
  id: string;
}

export interface DeliveryStartedResponse {
}

export interface CreateOrderRequest {
  meta: CreateOrderRequest_Meta | undefined;
  productIds: string[];
  address: CreateOrderRequest_Address | undefined;
  payment: CreateOrderRequest_Payment | undefined;
}

export interface CreateOrderRequest_Meta {
  user: CreateOrderRequest_Meta_UserPayload | undefined;
}

export interface CreateOrderRequest_Meta_UserPayload {
  sub: string;
}

export interface CreateOrderRequest_Address {
  name: string;
  steet: string;
  city: string;
  postalCode: string;
  country: string;
}

export interface CreateOrderRequest_Payment {
  paymentMethod: string;
  paymentName: string;
  cardNumber: string;
  expiryYear: string;
  expiryMonth: string;
  birthOrRegistration: string;
  passwordTwoDigits: string;
  amount: number;
}

export interface CreateOrderResponse {
  customer: CreateOrderResponse_Customer | undefined;
  products: CreateOrderResponse_Product[];
  deliveryAddress: CreateOrderResponse_DeliveryAddress | undefined;
  status: string;
  payment: CreateOrderResponse_Payment | undefined;
}

export interface CreateOrderResponse_Customer {
  userId: string;
  email: string;
  name: string;
}

export interface CreateOrderResponse_Product {
  productId: string;
  name: string;
  price: number;
}

export interface CreateOrderResponse_DeliveryAddress {
  name: string;
  street: string;
  city: string;
  postalCode: string;
  country: string;
}

export interface CreateOrderResponse_Payment {
  paymentId: string;
  paymentMethod: string;
  paymentName: string;
  amount: number;
}

function createBaseDeliveryStartedRequest(): DeliveryStartedRequest {
  return { id: "" };
}

export const DeliveryStartedRequest: MessageFns<DeliveryStartedRequest> = {
  encode(message: DeliveryStartedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeliveryStartedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeliveryStartedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeliveryStartedRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: DeliveryStartedRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeliveryStartedRequest>, I>>(base?: I): DeliveryStartedRequest {
    return DeliveryStartedRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeliveryStartedRequest>, I>>(object: I): DeliveryStartedRequest {
    const message = createBaseDeliveryStartedRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseDeliveryStartedResponse(): DeliveryStartedResponse {
  return {};
}

export const DeliveryStartedResponse: MessageFns<DeliveryStartedResponse> = {
  encode(_: DeliveryStartedResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeliveryStartedResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeliveryStartedResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): DeliveryStartedResponse {
    return {};
  },

  toJSON(_: DeliveryStartedResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<DeliveryStartedResponse>, I>>(base?: I): DeliveryStartedResponse {
    return DeliveryStartedResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeliveryStartedResponse>, I>>(_: I): DeliveryStartedResponse {
    const message = createBaseDeliveryStartedResponse();
    return message;
  },
};

function createBaseCreateOrderRequest(): CreateOrderRequest {
  return { meta: undefined, productIds: [], address: undefined, payment: undefined };
}

export const CreateOrderRequest: MessageFns<CreateOrderRequest> = {
  encode(message: CreateOrderRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.meta !== undefined) {
      CreateOrderRequest_Meta.encode(message.meta, writer.uint32(10).fork()).join();
    }
    for (const v of message.productIds) {
      writer.uint32(18).string(v!);
    }
    if (message.address !== undefined) {
      CreateOrderRequest_Address.encode(message.address, writer.uint32(26).fork()).join();
    }
    if (message.payment !== undefined) {
      CreateOrderRequest_Payment.encode(message.payment, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrderRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrderRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.meta = CreateOrderRequest_Meta.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.productIds.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.address = CreateOrderRequest_Address.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.payment = CreateOrderRequest_Payment.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateOrderRequest {
    return {
      meta: isSet(object.meta) ? CreateOrderRequest_Meta.fromJSON(object.meta) : undefined,
      productIds: globalThis.Array.isArray(object?.productIds)
        ? object.productIds.map((e: any) => globalThis.String(e))
        : [],
      address: isSet(object.address) ? CreateOrderRequest_Address.fromJSON(object.address) : undefined,
      payment: isSet(object.payment) ? CreateOrderRequest_Payment.fromJSON(object.payment) : undefined,
    };
  },

  toJSON(message: CreateOrderRequest): unknown {
    const obj: any = {};
    if (message.meta !== undefined) {
      obj.meta = CreateOrderRequest_Meta.toJSON(message.meta);
    }
    if (message.productIds?.length) {
      obj.productIds = message.productIds;
    }
    if (message.address !== undefined) {
      obj.address = CreateOrderRequest_Address.toJSON(message.address);
    }
    if (message.payment !== undefined) {
      obj.payment = CreateOrderRequest_Payment.toJSON(message.payment);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateOrderRequest>, I>>(base?: I): CreateOrderRequest {
    return CreateOrderRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateOrderRequest>, I>>(object: I): CreateOrderRequest {
    const message = createBaseCreateOrderRequest();
    message.meta = (object.meta !== undefined && object.meta !== null)
      ? CreateOrderRequest_Meta.fromPartial(object.meta)
      : undefined;
    message.productIds = object.productIds?.map((e) => e) || [];
    message.address = (object.address !== undefined && object.address !== null)
      ? CreateOrderRequest_Address.fromPartial(object.address)
      : undefined;
    message.payment = (object.payment !== undefined && object.payment !== null)
      ? CreateOrderRequest_Payment.fromPartial(object.payment)
      : undefined;
    return message;
  },
};

function createBaseCreateOrderRequest_Meta(): CreateOrderRequest_Meta {
  return { user: undefined };
}

export const CreateOrderRequest_Meta: MessageFns<CreateOrderRequest_Meta> = {
  encode(message: CreateOrderRequest_Meta, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== undefined) {
      CreateOrderRequest_Meta_UserPayload.encode(message.user, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrderRequest_Meta {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrderRequest_Meta();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = CreateOrderRequest_Meta_UserPayload.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateOrderRequest_Meta {
    return { user: isSet(object.user) ? CreateOrderRequest_Meta_UserPayload.fromJSON(object.user) : undefined };
  },

  toJSON(message: CreateOrderRequest_Meta): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = CreateOrderRequest_Meta_UserPayload.toJSON(message.user);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateOrderRequest_Meta>, I>>(base?: I): CreateOrderRequest_Meta {
    return CreateOrderRequest_Meta.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateOrderRequest_Meta>, I>>(object: I): CreateOrderRequest_Meta {
    const message = createBaseCreateOrderRequest_Meta();
    message.user = (object.user !== undefined && object.user !== null)
      ? CreateOrderRequest_Meta_UserPayload.fromPartial(object.user)
      : undefined;
    return message;
  },
};

function createBaseCreateOrderRequest_Meta_UserPayload(): CreateOrderRequest_Meta_UserPayload {
  return { sub: "" };
}

export const CreateOrderRequest_Meta_UserPayload: MessageFns<CreateOrderRequest_Meta_UserPayload> = {
  encode(message: CreateOrderRequest_Meta_UserPayload, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sub !== "") {
      writer.uint32(10).string(message.sub);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrderRequest_Meta_UserPayload {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrderRequest_Meta_UserPayload();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sub = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateOrderRequest_Meta_UserPayload {
    return { sub: isSet(object.sub) ? globalThis.String(object.sub) : "" };
  },

  toJSON(message: CreateOrderRequest_Meta_UserPayload): unknown {
    const obj: any = {};
    if (message.sub !== "") {
      obj.sub = message.sub;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateOrderRequest_Meta_UserPayload>, I>>(
    base?: I,
  ): CreateOrderRequest_Meta_UserPayload {
    return CreateOrderRequest_Meta_UserPayload.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateOrderRequest_Meta_UserPayload>, I>>(
    object: I,
  ): CreateOrderRequest_Meta_UserPayload {
    const message = createBaseCreateOrderRequest_Meta_UserPayload();
    message.sub = object.sub ?? "";
    return message;
  },
};

function createBaseCreateOrderRequest_Address(): CreateOrderRequest_Address {
  return { name: "", steet: "", city: "", postalCode: "", country: "" };
}

export const CreateOrderRequest_Address: MessageFns<CreateOrderRequest_Address> = {
  encode(message: CreateOrderRequest_Address, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.steet !== "") {
      writer.uint32(18).string(message.steet);
    }
    if (message.city !== "") {
      writer.uint32(26).string(message.city);
    }
    if (message.postalCode !== "") {
      writer.uint32(34).string(message.postalCode);
    }
    if (message.country !== "") {
      writer.uint32(42).string(message.country);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrderRequest_Address {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrderRequest_Address();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.steet = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.city = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.postalCode = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.country = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateOrderRequest_Address {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      steet: isSet(object.steet) ? globalThis.String(object.steet) : "",
      city: isSet(object.city) ? globalThis.String(object.city) : "",
      postalCode: isSet(object.postalCode) ? globalThis.String(object.postalCode) : "",
      country: isSet(object.country) ? globalThis.String(object.country) : "",
    };
  },

  toJSON(message: CreateOrderRequest_Address): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.steet !== "") {
      obj.steet = message.steet;
    }
    if (message.city !== "") {
      obj.city = message.city;
    }
    if (message.postalCode !== "") {
      obj.postalCode = message.postalCode;
    }
    if (message.country !== "") {
      obj.country = message.country;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateOrderRequest_Address>, I>>(base?: I): CreateOrderRequest_Address {
    return CreateOrderRequest_Address.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateOrderRequest_Address>, I>>(object: I): CreateOrderRequest_Address {
    const message = createBaseCreateOrderRequest_Address();
    message.name = object.name ?? "";
    message.steet = object.steet ?? "";
    message.city = object.city ?? "";
    message.postalCode = object.postalCode ?? "";
    message.country = object.country ?? "";
    return message;
  },
};

function createBaseCreateOrderRequest_Payment(): CreateOrderRequest_Payment {
  return {
    paymentMethod: "",
    paymentName: "",
    cardNumber: "",
    expiryYear: "",
    expiryMonth: "",
    birthOrRegistration: "",
    passwordTwoDigits: "",
    amount: 0,
  };
}

export const CreateOrderRequest_Payment: MessageFns<CreateOrderRequest_Payment> = {
  encode(message: CreateOrderRequest_Payment, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.paymentMethod !== "") {
      writer.uint32(10).string(message.paymentMethod);
    }
    if (message.paymentName !== "") {
      writer.uint32(18).string(message.paymentName);
    }
    if (message.cardNumber !== "") {
      writer.uint32(26).string(message.cardNumber);
    }
    if (message.expiryYear !== "") {
      writer.uint32(34).string(message.expiryYear);
    }
    if (message.expiryMonth !== "") {
      writer.uint32(42).string(message.expiryMonth);
    }
    if (message.birthOrRegistration !== "") {
      writer.uint32(50).string(message.birthOrRegistration);
    }
    if (message.passwordTwoDigits !== "") {
      writer.uint32(58).string(message.passwordTwoDigits);
    }
    if (message.amount !== 0) {
      writer.uint32(65).double(message.amount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrderRequest_Payment {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrderRequest_Payment();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.paymentMethod = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.paymentName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.cardNumber = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.expiryYear = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.expiryMonth = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.birthOrRegistration = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.passwordTwoDigits = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.amount = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateOrderRequest_Payment {
    return {
      paymentMethod: isSet(object.paymentMethod) ? globalThis.String(object.paymentMethod) : "",
      paymentName: isSet(object.paymentName) ? globalThis.String(object.paymentName) : "",
      cardNumber: isSet(object.cardNumber) ? globalThis.String(object.cardNumber) : "",
      expiryYear: isSet(object.expiryYear) ? globalThis.String(object.expiryYear) : "",
      expiryMonth: isSet(object.expiryMonth) ? globalThis.String(object.expiryMonth) : "",
      birthOrRegistration: isSet(object.birthOrRegistration) ? globalThis.String(object.birthOrRegistration) : "",
      passwordTwoDigits: isSet(object.passwordTwoDigits) ? globalThis.String(object.passwordTwoDigits) : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
    };
  },

  toJSON(message: CreateOrderRequest_Payment): unknown {
    const obj: any = {};
    if (message.paymentMethod !== "") {
      obj.paymentMethod = message.paymentMethod;
    }
    if (message.paymentName !== "") {
      obj.paymentName = message.paymentName;
    }
    if (message.cardNumber !== "") {
      obj.cardNumber = message.cardNumber;
    }
    if (message.expiryYear !== "") {
      obj.expiryYear = message.expiryYear;
    }
    if (message.expiryMonth !== "") {
      obj.expiryMonth = message.expiryMonth;
    }
    if (message.birthOrRegistration !== "") {
      obj.birthOrRegistration = message.birthOrRegistration;
    }
    if (message.passwordTwoDigits !== "") {
      obj.passwordTwoDigits = message.passwordTwoDigits;
    }
    if (message.amount !== 0) {
      obj.amount = message.amount;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateOrderRequest_Payment>, I>>(base?: I): CreateOrderRequest_Payment {
    return CreateOrderRequest_Payment.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateOrderRequest_Payment>, I>>(object: I): CreateOrderRequest_Payment {
    const message = createBaseCreateOrderRequest_Payment();
    message.paymentMethod = object.paymentMethod ?? "";
    message.paymentName = object.paymentName ?? "";
    message.cardNumber = object.cardNumber ?? "";
    message.expiryYear = object.expiryYear ?? "";
    message.expiryMonth = object.expiryMonth ?? "";
    message.birthOrRegistration = object.birthOrRegistration ?? "";
    message.passwordTwoDigits = object.passwordTwoDigits ?? "";
    message.amount = object.amount ?? 0;
    return message;
  },
};

function createBaseCreateOrderResponse(): CreateOrderResponse {
  return { customer: undefined, products: [], deliveryAddress: undefined, status: "", payment: undefined };
}

export const CreateOrderResponse: MessageFns<CreateOrderResponse> = {
  encode(message: CreateOrderResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.customer !== undefined) {
      CreateOrderResponse_Customer.encode(message.customer, writer.uint32(10).fork()).join();
    }
    for (const v of message.products) {
      CreateOrderResponse_Product.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.deliveryAddress !== undefined) {
      CreateOrderResponse_DeliveryAddress.encode(message.deliveryAddress, writer.uint32(26).fork()).join();
    }
    if (message.status !== "") {
      writer.uint32(34).string(message.status);
    }
    if (message.payment !== undefined) {
      CreateOrderResponse_Payment.encode(message.payment, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrderResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrderResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.customer = CreateOrderResponse_Customer.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.products.push(CreateOrderResponse_Product.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.deliveryAddress = CreateOrderResponse_DeliveryAddress.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.payment = CreateOrderResponse_Payment.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateOrderResponse {
    return {
      customer: isSet(object.customer) ? CreateOrderResponse_Customer.fromJSON(object.customer) : undefined,
      products: globalThis.Array.isArray(object?.products)
        ? object.products.map((e: any) => CreateOrderResponse_Product.fromJSON(e))
        : [],
      deliveryAddress: isSet(object.deliveryAddress)
        ? CreateOrderResponse_DeliveryAddress.fromJSON(object.deliveryAddress)
        : undefined,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      payment: isSet(object.payment) ? CreateOrderResponse_Payment.fromJSON(object.payment) : undefined,
    };
  },

  toJSON(message: CreateOrderResponse): unknown {
    const obj: any = {};
    if (message.customer !== undefined) {
      obj.customer = CreateOrderResponse_Customer.toJSON(message.customer);
    }
    if (message.products?.length) {
      obj.products = message.products.map((e) => CreateOrderResponse_Product.toJSON(e));
    }
    if (message.deliveryAddress !== undefined) {
      obj.deliveryAddress = CreateOrderResponse_DeliveryAddress.toJSON(message.deliveryAddress);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.payment !== undefined) {
      obj.payment = CreateOrderResponse_Payment.toJSON(message.payment);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateOrderResponse>, I>>(base?: I): CreateOrderResponse {
    return CreateOrderResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateOrderResponse>, I>>(object: I): CreateOrderResponse {
    const message = createBaseCreateOrderResponse();
    message.customer = (object.customer !== undefined && object.customer !== null)
      ? CreateOrderResponse_Customer.fromPartial(object.customer)
      : undefined;
    message.products = object.products?.map((e) => CreateOrderResponse_Product.fromPartial(e)) || [];
    message.deliveryAddress = (object.deliveryAddress !== undefined && object.deliveryAddress !== null)
      ? CreateOrderResponse_DeliveryAddress.fromPartial(object.deliveryAddress)
      : undefined;
    message.status = object.status ?? "";
    message.payment = (object.payment !== undefined && object.payment !== null)
      ? CreateOrderResponse_Payment.fromPartial(object.payment)
      : undefined;
    return message;
  },
};

function createBaseCreateOrderResponse_Customer(): CreateOrderResponse_Customer {
  return { userId: "", email: "", name: "" };
}

export const CreateOrderResponse_Customer: MessageFns<CreateOrderResponse_Customer> = {
  encode(message: CreateOrderResponse_Customer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrderResponse_Customer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrderResponse_Customer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateOrderResponse_Customer {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: CreateOrderResponse_Customer): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateOrderResponse_Customer>, I>>(base?: I): CreateOrderResponse_Customer {
    return CreateOrderResponse_Customer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateOrderResponse_Customer>, I>>(object: I): CreateOrderResponse_Customer {
    const message = createBaseCreateOrderResponse_Customer();
    message.userId = object.userId ?? "";
    message.email = object.email ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseCreateOrderResponse_Product(): CreateOrderResponse_Product {
  return { productId: "", name: "", price: 0 };
}

export const CreateOrderResponse_Product: MessageFns<CreateOrderResponse_Product> = {
  encode(message: CreateOrderResponse_Product, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.productId !== "") {
      writer.uint32(10).string(message.productId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.price !== 0) {
      writer.uint32(24).int32(message.price);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrderResponse_Product {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrderResponse_Product();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.productId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.price = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateOrderResponse_Product {
    return {
      productId: isSet(object.productId) ? globalThis.String(object.productId) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      price: isSet(object.price) ? globalThis.Number(object.price) : 0,
    };
  },

  toJSON(message: CreateOrderResponse_Product): unknown {
    const obj: any = {};
    if (message.productId !== "") {
      obj.productId = message.productId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.price !== 0) {
      obj.price = Math.round(message.price);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateOrderResponse_Product>, I>>(base?: I): CreateOrderResponse_Product {
    return CreateOrderResponse_Product.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateOrderResponse_Product>, I>>(object: I): CreateOrderResponse_Product {
    const message = createBaseCreateOrderResponse_Product();
    message.productId = object.productId ?? "";
    message.name = object.name ?? "";
    message.price = object.price ?? 0;
    return message;
  },
};

function createBaseCreateOrderResponse_DeliveryAddress(): CreateOrderResponse_DeliveryAddress {
  return { name: "", street: "", city: "", postalCode: "", country: "" };
}

export const CreateOrderResponse_DeliveryAddress: MessageFns<CreateOrderResponse_DeliveryAddress> = {
  encode(message: CreateOrderResponse_DeliveryAddress, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.street !== "") {
      writer.uint32(18).string(message.street);
    }
    if (message.city !== "") {
      writer.uint32(26).string(message.city);
    }
    if (message.postalCode !== "") {
      writer.uint32(34).string(message.postalCode);
    }
    if (message.country !== "") {
      writer.uint32(42).string(message.country);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrderResponse_DeliveryAddress {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrderResponse_DeliveryAddress();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.street = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.city = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.postalCode = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.country = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateOrderResponse_DeliveryAddress {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      street: isSet(object.street) ? globalThis.String(object.street) : "",
      city: isSet(object.city) ? globalThis.String(object.city) : "",
      postalCode: isSet(object.postalCode) ? globalThis.String(object.postalCode) : "",
      country: isSet(object.country) ? globalThis.String(object.country) : "",
    };
  },

  toJSON(message: CreateOrderResponse_DeliveryAddress): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.street !== "") {
      obj.street = message.street;
    }
    if (message.city !== "") {
      obj.city = message.city;
    }
    if (message.postalCode !== "") {
      obj.postalCode = message.postalCode;
    }
    if (message.country !== "") {
      obj.country = message.country;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateOrderResponse_DeliveryAddress>, I>>(
    base?: I,
  ): CreateOrderResponse_DeliveryAddress {
    return CreateOrderResponse_DeliveryAddress.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateOrderResponse_DeliveryAddress>, I>>(
    object: I,
  ): CreateOrderResponse_DeliveryAddress {
    const message = createBaseCreateOrderResponse_DeliveryAddress();
    message.name = object.name ?? "";
    message.street = object.street ?? "";
    message.city = object.city ?? "";
    message.postalCode = object.postalCode ?? "";
    message.country = object.country ?? "";
    return message;
  },
};

function createBaseCreateOrderResponse_Payment(): CreateOrderResponse_Payment {
  return { paymentId: "", paymentMethod: "", paymentName: "", amount: 0 };
}

export const CreateOrderResponse_Payment: MessageFns<CreateOrderResponse_Payment> = {
  encode(message: CreateOrderResponse_Payment, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.paymentId !== "") {
      writer.uint32(10).string(message.paymentId);
    }
    if (message.paymentMethod !== "") {
      writer.uint32(18).string(message.paymentMethod);
    }
    if (message.paymentName !== "") {
      writer.uint32(26).string(message.paymentName);
    }
    if (message.amount !== 0) {
      writer.uint32(33).double(message.amount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateOrderResponse_Payment {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateOrderResponse_Payment();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.paymentId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.paymentMethod = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.paymentName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 33) {
            break;
          }

          message.amount = reader.double();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateOrderResponse_Payment {
    return {
      paymentId: isSet(object.paymentId) ? globalThis.String(object.paymentId) : "",
      paymentMethod: isSet(object.paymentMethod) ? globalThis.String(object.paymentMethod) : "",
      paymentName: isSet(object.paymentName) ? globalThis.String(object.paymentName) : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
    };
  },

  toJSON(message: CreateOrderResponse_Payment): unknown {
    const obj: any = {};
    if (message.paymentId !== "") {
      obj.paymentId = message.paymentId;
    }
    if (message.paymentMethod !== "") {
      obj.paymentMethod = message.paymentMethod;
    }
    if (message.paymentName !== "") {
      obj.paymentName = message.paymentName;
    }
    if (message.amount !== 0) {
      obj.amount = message.amount;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateOrderResponse_Payment>, I>>(base?: I): CreateOrderResponse_Payment {
    return CreateOrderResponse_Payment.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateOrderResponse_Payment>, I>>(object: I): CreateOrderResponse_Payment {
    const message = createBaseCreateOrderResponse_Payment();
    message.paymentId = object.paymentId ?? "";
    message.paymentMethod = object.paymentMethod ?? "";
    message.paymentName = object.paymentName ?? "";
    message.amount = object.amount ?? 0;
    return message;
  },
};

export interface OrderService {
  DeliveryStarted(request: DeliveryStartedRequest, metadata?: Metadata): Promise<DeliveryStartedResponse>;
  CreateOrder(request: CreateOrderRequest, metadata?: Metadata): Promise<CreateOrderResponse>;
}

export const OrderServiceServiceName = "order.OrderService";
export class OrderServiceClientImpl implements OrderService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || OrderServiceServiceName;
    this.rpc = rpc;
    this.DeliveryStarted = this.DeliveryStarted.bind(this);
    this.CreateOrder = this.CreateOrder.bind(this);
  }
  DeliveryStarted(request: DeliveryStartedRequest, metadata?: Metadata): Promise<DeliveryStartedResponse> {
    const data = DeliveryStartedRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "DeliveryStarted", data, metadata);
    return promise.then((data) => DeliveryStartedResponse.decode(new BinaryReader(data)));
  }

  CreateOrder(request: CreateOrderRequest, metadata?: Metadata): Promise<CreateOrderResponse> {
    const data = CreateOrderRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateOrder", data, metadata);
    return promise.then((data) => CreateOrderResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array, metadata?: Metadata): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
