// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: proto/payment.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { Metadata } from "@grpc/grpc-js";

export const protobufPackage = "payment";

export interface MakePaymentRequest {
  orderId: string;
  paymentMethod: string;
  paymentName: string;
  cardNumber: string;
  expiryYear: string;
  expiryMonth: string;
  birthOrRegistration: string;
  amount: number;
  userEmail: string;
  passwordTwoDigits: string;
}

export interface MakePaymentResponse {
  id: string;
  paymentStatus: string;
  paymentMethod: string;
}

function createBaseMakePaymentRequest(): MakePaymentRequest {
  return {
    orderId: "",
    paymentMethod: "",
    paymentName: "",
    cardNumber: "",
    expiryYear: "",
    expiryMonth: "",
    birthOrRegistration: "",
    amount: 0,
    userEmail: "",
    passwordTwoDigits: "",
  };
}

export const MakePaymentRequest: MessageFns<MakePaymentRequest> = {
  encode(message: MakePaymentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.orderId !== "") {
      writer.uint32(10).string(message.orderId);
    }
    if (message.paymentMethod !== "") {
      writer.uint32(18).string(message.paymentMethod);
    }
    if (message.paymentName !== "") {
      writer.uint32(26).string(message.paymentName);
    }
    if (message.cardNumber !== "") {
      writer.uint32(34).string(message.cardNumber);
    }
    if (message.expiryYear !== "") {
      writer.uint32(42).string(message.expiryYear);
    }
    if (message.expiryMonth !== "") {
      writer.uint32(50).string(message.expiryMonth);
    }
    if (message.birthOrRegistration !== "") {
      writer.uint32(58).string(message.birthOrRegistration);
    }
    if (message.amount !== 0) {
      writer.uint32(65).double(message.amount);
    }
    if (message.userEmail !== "") {
      writer.uint32(74).string(message.userEmail);
    }
    if (message.passwordTwoDigits !== "") {
      writer.uint32(82).string(message.passwordTwoDigits);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MakePaymentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMakePaymentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.orderId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.paymentMethod = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.paymentName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.cardNumber = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.expiryYear = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.expiryMonth = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.birthOrRegistration = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 65) {
            break;
          }

          message.amount = reader.double();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.userEmail = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.passwordTwoDigits = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MakePaymentRequest {
    return {
      orderId: isSet(object.orderId) ? globalThis.String(object.orderId) : "",
      paymentMethod: isSet(object.paymentMethod) ? globalThis.String(object.paymentMethod) : "",
      paymentName: isSet(object.paymentName) ? globalThis.String(object.paymentName) : "",
      cardNumber: isSet(object.cardNumber) ? globalThis.String(object.cardNumber) : "",
      expiryYear: isSet(object.expiryYear) ? globalThis.String(object.expiryYear) : "",
      expiryMonth: isSet(object.expiryMonth) ? globalThis.String(object.expiryMonth) : "",
      birthOrRegistration: isSet(object.birthOrRegistration) ? globalThis.String(object.birthOrRegistration) : "",
      amount: isSet(object.amount) ? globalThis.Number(object.amount) : 0,
      userEmail: isSet(object.userEmail) ? globalThis.String(object.userEmail) : "",
      passwordTwoDigits: isSet(object.passwordTwoDigits) ? globalThis.String(object.passwordTwoDigits) : "",
    };
  },

  toJSON(message: MakePaymentRequest): unknown {
    const obj: any = {};
    if (message.orderId !== "") {
      obj.orderId = message.orderId;
    }
    if (message.paymentMethod !== "") {
      obj.paymentMethod = message.paymentMethod;
    }
    if (message.paymentName !== "") {
      obj.paymentName = message.paymentName;
    }
    if (message.cardNumber !== "") {
      obj.cardNumber = message.cardNumber;
    }
    if (message.expiryYear !== "") {
      obj.expiryYear = message.expiryYear;
    }
    if (message.expiryMonth !== "") {
      obj.expiryMonth = message.expiryMonth;
    }
    if (message.birthOrRegistration !== "") {
      obj.birthOrRegistration = message.birthOrRegistration;
    }
    if (message.amount !== 0) {
      obj.amount = message.amount;
    }
    if (message.userEmail !== "") {
      obj.userEmail = message.userEmail;
    }
    if (message.passwordTwoDigits !== "") {
      obj.passwordTwoDigits = message.passwordTwoDigits;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MakePaymentRequest>, I>>(base?: I): MakePaymentRequest {
    return MakePaymentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MakePaymentRequest>, I>>(object: I): MakePaymentRequest {
    const message = createBaseMakePaymentRequest();
    message.orderId = object.orderId ?? "";
    message.paymentMethod = object.paymentMethod ?? "";
    message.paymentName = object.paymentName ?? "";
    message.cardNumber = object.cardNumber ?? "";
    message.expiryYear = object.expiryYear ?? "";
    message.expiryMonth = object.expiryMonth ?? "";
    message.birthOrRegistration = object.birthOrRegistration ?? "";
    message.amount = object.amount ?? 0;
    message.userEmail = object.userEmail ?? "";
    message.passwordTwoDigits = object.passwordTwoDigits ?? "";
    return message;
  },
};

function createBaseMakePaymentResponse(): MakePaymentResponse {
  return { id: "", paymentStatus: "", paymentMethod: "" };
}

export const MakePaymentResponse: MessageFns<MakePaymentResponse> = {
  encode(message: MakePaymentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.paymentStatus !== "") {
      writer.uint32(18).string(message.paymentStatus);
    }
    if (message.paymentMethod !== "") {
      writer.uint32(26).string(message.paymentMethod);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MakePaymentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMakePaymentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.paymentStatus = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.paymentMethod = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MakePaymentResponse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      paymentStatus: isSet(object.paymentStatus) ? globalThis.String(object.paymentStatus) : "",
      paymentMethod: isSet(object.paymentMethod) ? globalThis.String(object.paymentMethod) : "",
    };
  },

  toJSON(message: MakePaymentResponse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.paymentStatus !== "") {
      obj.paymentStatus = message.paymentStatus;
    }
    if (message.paymentMethod !== "") {
      obj.paymentMethod = message.paymentMethod;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MakePaymentResponse>, I>>(base?: I): MakePaymentResponse {
    return MakePaymentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MakePaymentResponse>, I>>(object: I): MakePaymentResponse {
    const message = createBaseMakePaymentResponse();
    message.id = object.id ?? "";
    message.paymentStatus = object.paymentStatus ?? "";
    message.paymentMethod = object.paymentMethod ?? "";
    return message;
  },
};

export interface PaymentService {
  MakePayment(request: MakePaymentRequest, metadata?: Metadata): Promise<MakePaymentResponse>;
}

export const PaymentServiceServiceName = "payment.PaymentService";
export class PaymentServiceClientImpl implements PaymentService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || PaymentServiceServiceName;
    this.rpc = rpc;
    this.MakePayment = this.MakePayment.bind(this);
  }
  MakePayment(request: MakePaymentRequest, metadata?: Metadata): Promise<MakePaymentResponse> {
    const data = MakePaymentRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "MakePayment", data, metadata);
    return promise.then((data) => MakePaymentResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array, metadata?: Metadata): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
