// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.2
//   protoc               v6.33.4
// source: proto/product.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { Metadata } from "@grpc/grpc-js";

export const protobufPackage = "product";

/**
 * 아무 값도 안넣더라도 message request는 무조건 만들어야 한다.
 * input params이 없더라도, message request를 만드는 게 확장성이 더 있기 때문이다.
 */
export interface CreateSamplesRequest {
}

export interface CreateSamplesResponse {
  success: boolean;
}

export interface GetProductInfoRequest {
  productIds: string[];
}

export interface GetProductInfoResponse {
  /** productInfo[] */
  productInfos: GetProductInfoResponse_ProductInfo[];
}

export interface GetProductInfoResponse_ProductInfo {
  id: string;
  name: string;
  price: number;
  description: string;
  image: string;
}

function createBaseCreateSamplesRequest(): CreateSamplesRequest {
  return {};
}

export const CreateSamplesRequest: MessageFns<CreateSamplesRequest> = {
  encode(_: CreateSamplesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSamplesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSamplesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CreateSamplesRequest {
    return {};
  },

  toJSON(_: CreateSamplesRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateSamplesRequest>, I>>(base?: I): CreateSamplesRequest {
    return CreateSamplesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateSamplesRequest>, I>>(_: I): CreateSamplesRequest {
    const message = createBaseCreateSamplesRequest();
    return message;
  },
};

function createBaseCreateSamplesResponse(): CreateSamplesResponse {
  return { success: false };
}

export const CreateSamplesResponse: MessageFns<CreateSamplesResponse> = {
  encode(message: CreateSamplesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateSamplesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSamplesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateSamplesResponse {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: CreateSamplesResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateSamplesResponse>, I>>(base?: I): CreateSamplesResponse {
    return CreateSamplesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateSamplesResponse>, I>>(object: I): CreateSamplesResponse {
    const message = createBaseCreateSamplesResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseGetProductInfoRequest(): GetProductInfoRequest {
  return { productIds: [] };
}

export const GetProductInfoRequest: MessageFns<GetProductInfoRequest> = {
  encode(message: GetProductInfoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.productIds) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetProductInfoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetProductInfoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.productIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetProductInfoRequest {
    return {
      productIds: globalThis.Array.isArray(object?.productIds)
        ? object.productIds.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: GetProductInfoRequest): unknown {
    const obj: any = {};
    if (message.productIds?.length) {
      obj.productIds = message.productIds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetProductInfoRequest>, I>>(base?: I): GetProductInfoRequest {
    return GetProductInfoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetProductInfoRequest>, I>>(object: I): GetProductInfoRequest {
    const message = createBaseGetProductInfoRequest();
    message.productIds = object.productIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetProductInfoResponse(): GetProductInfoResponse {
  return { productInfos: [] };
}

export const GetProductInfoResponse: MessageFns<GetProductInfoResponse> = {
  encode(message: GetProductInfoResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.productInfos) {
      GetProductInfoResponse_ProductInfo.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetProductInfoResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetProductInfoResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.productInfos.push(GetProductInfoResponse_ProductInfo.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetProductInfoResponse {
    return {
      productInfos: globalThis.Array.isArray(object?.productInfos)
        ? object.productInfos.map((e: any) => GetProductInfoResponse_ProductInfo.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetProductInfoResponse): unknown {
    const obj: any = {};
    if (message.productInfos?.length) {
      obj.productInfos = message.productInfos.map((e) => GetProductInfoResponse_ProductInfo.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetProductInfoResponse>, I>>(base?: I): GetProductInfoResponse {
    return GetProductInfoResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetProductInfoResponse>, I>>(object: I): GetProductInfoResponse {
    const message = createBaseGetProductInfoResponse();
    message.productInfos = object.productInfos?.map((e) => GetProductInfoResponse_ProductInfo.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetProductInfoResponse_ProductInfo(): GetProductInfoResponse_ProductInfo {
  return { id: "", name: "", price: 0, description: "", image: "" };
}

export const GetProductInfoResponse_ProductInfo: MessageFns<GetProductInfoResponse_ProductInfo> = {
  encode(message: GetProductInfoResponse_ProductInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.price !== 0) {
      writer.uint32(24).int32(message.price);
    }
    if (message.description !== "") {
      writer.uint32(34).string(message.description);
    }
    if (message.image !== "") {
      writer.uint32(42).string(message.image);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetProductInfoResponse_ProductInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetProductInfoResponse_ProductInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.price = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.image = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetProductInfoResponse_ProductInfo {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      price: isSet(object.price) ? globalThis.Number(object.price) : 0,
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      image: isSet(object.image) ? globalThis.String(object.image) : "",
    };
  },

  toJSON(message: GetProductInfoResponse_ProductInfo): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.price !== 0) {
      obj.price = Math.round(message.price);
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.image !== "") {
      obj.image = message.image;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetProductInfoResponse_ProductInfo>, I>>(
    base?: I,
  ): GetProductInfoResponse_ProductInfo {
    return GetProductInfoResponse_ProductInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetProductInfoResponse_ProductInfo>, I>>(
    object: I,
  ): GetProductInfoResponse_ProductInfo {
    const message = createBaseGetProductInfoResponse_ProductInfo();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.price = object.price ?? 0;
    message.description = object.description ?? "";
    message.image = object.image ?? "";
    return message;
  },
};

export interface ProductService {
  createSamples(request: CreateSamplesRequest, metadata?: Metadata): Promise<CreateSamplesResponse>;
  getProductInfo(request: GetProductInfoRequest, metadata?: Metadata): Promise<GetProductInfoResponse>;
}

export const ProductServiceServiceName = "product.ProductService";
export class ProductServiceClientImpl implements ProductService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || ProductServiceServiceName;
    this.rpc = rpc;
    this.createSamples = this.createSamples.bind(this);
    this.getProductInfo = this.getProductInfo.bind(this);
  }
  createSamples(request: CreateSamplesRequest, metadata?: Metadata): Promise<CreateSamplesResponse> {
    const data = CreateSamplesRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateSamples", data, metadata);
    return promise.then((data) => CreateSamplesResponse.decode(new BinaryReader(data)));
  }

  getProductInfo(request: GetProductInfoRequest, metadata?: Metadata): Promise<GetProductInfoResponse> {
    const data = GetProductInfoRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetProductInfo", data, metadata);
    return promise.then((data) => GetProductInfoResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array, metadata?: Metadata): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
